[package]
name = "job_owner_rs"
version = "0.1.0"
authors = ["douro"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "*"
serde_json = "1.0"
serde = { version = "1.0.100", features = ["derive"] }